//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int ContactID { get; set; }
        public int EmployeeID { get; set; }
        public string InternalPhone { get; set; }
        public string CityPhone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
